project_name: gitsu

env:
  - GO111MODULE=on

before:
  hooks:
    - go mod tidy

builds:
  - main: .
    binary: git-su
    ldflags: -s -w -X main.version={{.Version}} -X main.commit={{.ShortCommit}} -X main.date={{.Date}}

archives:
  - replacements:
      darwin: darwin
      linux: linux
      windows: windows
      amd64: x86_64
    files:
      - LICENSE
      - CREDITS

release:
  prerelease: auto

brews:
  - tap:
      owner: matsuyoshi30
      name: homebrew-gitsu
    commit_author:
      name: goreleaserbot
      email: goreleaser@carlosbecker.com
    homepage: 'https://github.com/matsuyoshi30/gitsu'
    description: 'Switch git user easily'
    install: |
      bin.install "git-su"
